Repository cdapio/cdap-ui, pull requests merged in 2021-09, with the labels that each got.

#199 Adds styled-components
  .babelrc
  package.json
  yarn.lock
Labels: cla: yes

#200 Upgrade react & react dom from 16 to 17
  package.json
  yarn.lock
Labels: cla: yes

#203 [CDAP-18438] Update develop Cloud Build settings so Cypress tests can be run
  cloudbuild.yaml
  sandboxjs/bamboo_plan_info.json
Labels: cla: yes

#204 CDAP - 18439 | check if widget props exist in memory textbox
  app/cdap/components/AbstractWidget/MemoryTextbox/index.js
  app/cdap/components/Replicator/ConfigDisplay/PluginConfigDisplay/index.tsx
Labels: UI, cla: yes, 6.5.1

#206 CDAP 18335 | add can edit while open to two error banners
  app/cdap/components/DataPrepConnections/PluginConnectionBrowser/index.tsx
  app/cdap/components/PipelineList/DeployedPipelineView/index.tsx
Labels: UI, cla: yes

#209 [CDAP-18453] Update Material-ui to handle changes in new React version
  app/cdap/components/AbstractWidget/Comment/CommentBox.tsx
  app/cdap/components/AbstractWidget/Comment/CommentIcon.tsx
  app/cdap/components/AbstractWidget/Comment/CommentMenu.tsx
  app/cdap/components/AbstractWidget/Comment/index.tsx
  app/cdap/components/PipelineCanvasActions/PipelineCommentsActionBtn.tsx
  app/cdap/components/ThemeWrapper/index.tsx
  package.json
  yarn.lock
Labels: bug, cla: yes

#207 Adds metadata home page in react app
  app/cdap/components/AppHeader/AppDrawer/AppDrawer.tsx
  app/cdap/components/Home/index.js
  app/cdap/components/Metadata/Home/index.tsx
  app/cdap/components/Metadata/index.tsx
  app/cdap/services/ThemeHelper.ts
  app/cdap/text/text-en.yaml
  app/tracker/routes.js
Labels: cla: yes

#205 Cherry pick #204 into 6.5 | check if widget props exist before using min/max
  app/cdap/components/AbstractWidget/MemoryTextbox/index.js
  app/cdap/components/Replicator/ConfigDisplay/PluginConfigDisplay/index.tsx
Labels: cherry-pick, 6.5, cla: yes

#210 [CDAP-18453] Fix LogViewer event propagation for new React version
  app/cdap/components/Popover/index.js
Labels: bug, cla: yes

#211 Bugfix - use the shorthand for the array constructor instead of array.apply
  app/cdap/components/PipelineSummary/RunsGraphHelpers.js
Labels: UI, cla: yes

#212 [CDAP-18423] Fix browsing for GCS connections
  app/cdap/components/Connections/Browser/GenericBrowser/Breadcrumb.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
Labels: bug, cla: yes

#196 Fix left nav menu overlapping in smaller viewports
  app/cdap/components/AppHeader/AppDrawer/AppDrawer.tsx
Labels: cla: yes

#213 [CDAP-18423] Fix browsing for GCS connections for 6.5
  app/cdap/components/Connections/Browser/GenericBrowser/Breadcrumb.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
Labels: bug, cherry-pick, cla: yes, 6.5.1
