Repository cdapio/cdap-ui, pull requests merged in 2021-06, with the labels that each got.

#30 [CDAP-17766] Make value of runtime arguments key-value pair to be textarea to allow newline
  app/cdap/components/AbstractWidget/AbstractMultiRowWidget/AbstractRow.tsx
  app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/RuntimeArgsRow.tsx
  app/cdap/components/PipelineDetails/RunLevelInfo/RunConfigs.js
  app/cdap/components/PipelineDetails/RunLevelInfo/RunLevelInfo.scss
  cypress/integration/pipeline.runtimeargs.spec.ts
  cypress/support/commands.ts
Labels: 6.5

#35 [CDAP-17874] Add ability to edit connection
  app/cdap/api/connections.ts
  app/cdap/components/Alert/index.js
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/index.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/Create/reducer.ts
  app/cdap/components/Connections/CreateConnectionModal/index.tsx
  app/cdap/components/NamespaceAdmin/Connections.tsx
Labels: 6.5

#37 [CDAP-17867] Pushdown Config UI
  app/cdap/components/PipelineConfigurations/ConfigurationsContent/ConfigurationsContent.scss
  app/cdap/components/PushdownConfig/index.tsx
  app/cdap/components/Replicator/Create/Content/PluginConfig/index.tsx
  app/cdap/components/Replicator/Create/index.tsx
  app/cdap/components/Replicator/Detail/index.tsx
  app/cdap/components/Replicator/utilities/index.ts
  app/cdap/services/PluginUtilities/index.ts
  app/common/cask-shared-components.js
  app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config-ctrl.js
  app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config.html
  app/directives/react-components/index.js
  app/hydrator/services/create/stores/config-store.js
Labels: cla: yes

#36 [CDAP-18038] Empty and error messaging to match app standard
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/text/text-en.yaml
Labels: 6.5, UI, cla: yes

#39 [CDAP-17878] Integrates Wrangler UI with V2 wrangler API
  app/cdap/api/connections.ts
  app/cdap/api/dataprep.js
  app/cdap/components/AbstractWidget/WranglerEditor/index.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/apiHelpers.ts
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/Browser/SidePanel/apiHelpers.ts
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
  app/cdap/components/Connections/Browser/index.tsx
  app/cdap/components/Connections/ConnectionsContext/index.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/Create/reducer.ts
  app/cdap/components/Connections/CreateConnectionBtn/index.tsx
  app/cdap/components/Connections/CreateConnectionModal/index.tsx
  app/cdap/components/Connections/Home.tsx
  app/cdap/components/Connections/Routes.tsx
  app/cdap/components/Connections/index.tsx
  app/cdap/components/DataPrep/DataPrepTable/index.js
  app/cdap/components/DataPrep/Directives/DropColumn/index.js
  app/cdap/components/DataPrep/TopPanel/index.js
  app/cdap/components/DataPrep/WorkspaceTabs/WorkspaceTab/index.js
  app/cdap/components/DataPrep/WorkspaceTabs/index.js
  app/cdap/components/DataPrep/helper.js
  app/cdap/components/DataPrep/index.js
  app/cdap/components/DataPrep/store/DataPrepActionCreator.js
  app/cdap/components/DataPrepConnections/PluginConnectionBrowser/index.tsx
  app/cdap/components/DataPrepHome/DataPrepHome.scss
  app/cdap/components/DataPrepHome/index.js
  app/cdap/components/PipelineContextMenu/WranglerConnection/index.tsx
Labels: 6.5, cla: yes

#42 [CDAP-18020] Add entity count to new connection browser
  app/cdap/components/Connections/Browser/GenericBrowser/EntityCount.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
Labels: 6.5, UI, cla: yes

#43 [CDAP-17879] Modify API usage to navigate from wrangler to pipeline
  app/cdap/components/DataPrep/TopPanel/AddToPipelineModal.js
  app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
Labels: 6.5, cla: yes

#44 [CDAP-17878] Add ability to browse connection from pipeline
  app/cdap/api/connections.ts
  app/cdap/components/AbstractWidget/ConnectionsWidget/index.tsx
  app/cdap/components/ConfigurationGroup/PropertyRow/index.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/apiHelpers.ts
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/ConnectionsContext/index.tsx
  app/cdap/components/Connections/index.tsx
  app/cdap/components/DataPrepConnections/PluginConnectionBrowser/index.tsx
  app/cdap/components/PipelineModal/index.tsx
Labels: cla: yes

#46 Wrangler Fixes
  app/cdap/components/Connections/ConnectionsContext/index.tsx
  app/cdap/components/Connections/index.tsx
  app/cdap/components/DataPrep/TopPanel/SchemaModal.js
  app/cdap/components/DataPrep/TopPanel/index.js
  app/cdap/components/DataPrep/store/DataPrepActionCreator.js
  app/cdap/components/DataPrepHome/index.js
Labels: cla: yes

#45 [CDAP-17883] Remove condition to not hide required properties in conf…
  app/cdap/components/ConfigurationGroup/utilities/DynamicPluginFilters.ts
Labels: cla: yes

#47 [CDAP-17885] adds schema name to table display name
  app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/NoIssuesTables/index.tsx
  app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/WithIssuesTables/index.tsx
Labels: UI, bug, cla: yes

#48 [CDAP-17915] Adds schema name to table name for search filtering
  app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  app/cdap/components/Replicator/Create/Content/Summary/TableList/index.tsx
  app/cdap/components/Replicator/Detail/Overview/TablesList/index.tsx
Labels: UI, bug, cla: yes

#53 [CDAP-17867] Add pushdown ui to post-deploy ui, remove from studio
  app/cdap/components/PipelineConfigurations/ConfigurationsContent/PushdownTabContent.tsx
  app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
  app/cdap/components/PipelineConfigurations/Store/index.js
  app/cdap/components/PipelineConfigurations/TabConfig.js
  app/cdap/components/PipelineConfigurations/index.js
  app/cdap/components/PushdownConfig/index.tsx
  app/cdap/text/text-en.yaml
  app/common/cask-shared-components.js
  app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config-ctrl.js
  app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config.html
  app/directives/react-components/index.js
  app/hydrator/services/create/stores/config-store.js
Labels: cla: yes

#49 [CDAP-17510] Disables checkbox for selecting column on table replication if primary key
  app/cdap/components/Replicator/Create/Content/SelectColumns/index.tsx
  app/cdap/text/text-en.yaml
Labels: UI, bug, cla: yes

#51 Update unit test node version to 14 for active LTS and new JS features
  .github/workflows/node.js.yml
  package.json
  pom.xml
Labels: 6.5, UI, cla: yes

#55 Set node version for build to 14.17.1
  pom.xml
Labels: bug, cla: yes

#56 Set node back to 10.16 to avoid issues with dependencies
  .github/workflows/node.js.yml
  package.json
  pom.xml
Labels: 6.5, UI, cla: yes

#50 [CDAP-18040] Type-specific formatting for connection browser table
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/services/DataFormatter/__tests__/DataFormatter.test.ts
  app/cdap/services/DataFormatter/index.ts
Labels: 6.5, UI, cla: yes

#58 Bump up snapshot version after cutting branch for release 6.5
  pom.xml
Labels: cla: yes

#52 [CDAP-18069] Test connection during connection creation with new API
  app/cdap/api/connections.ts
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/index.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/Create/reducer.ts
  app/cdap/components/ThemeWrapper/colors.ts
  app/cdap/styles/colors.scss
Labels: 6.5, UI, cla: yes

#57 [CDAP-18040] Type-specific formatting for connection browser table for 6.5
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/services/DataFormatter/__tests__/DataFormatter.test.ts
  app/cdap/services/DataFormatter/index.ts
Labels: 6.5, UI, cherry-pick, cla: yes

#62 E2E: Use 6.5 branch of the CDAP sandbox build (6.5 branch)
  sandboxjs/bamboo_plan_info.json
Labels: 6.5, UI, cla: yes

#61 [CDAP-18069] Test connection during connection creation with new API for 6.5
  app/cdap/api/connections.ts
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/index.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/Create/reducer.ts
  app/cdap/components/ThemeWrapper/colors.ts
  app/cdap/styles/colors.scss
Labels: 6.5, UI, cherry-pick, cla: yes

#64 [CDAP-18078] [CDAP-18077] Connection browser: icons, widths, non-sample entities
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Table/TableCell.tsx
Labels: UI, cla: yes

#65 Fix connection managements bugs
  app/cdap/components/AbstractWidget/ConnectionsWidget/index.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/CreateConnectionModal/index.tsx
  app/cdap/components/Home/index.js
  app/cdap/components/NamespaceAdmin/Tabs.tsx
  app/cdap/components/PipelineConfigurations/ConfigurationsContent/PushdownTabContent.tsx
  app/cdap/components/PushdownConfig/index.tsx
  app/cdap/components/Table/TableCell.tsx
Labels: cla: yes

#67 [CDAP-18078] [CDAP-18077] Connection browser: icons, widths, non-sample entities for 6.5
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Table/TableCell.tsx
Labels: 6.5, UI, cherry-pick, cla: yes

#66 [CDAP-18108] Organized connection by types instead of categories
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/Connections/Browser/SidePanel/apiHelpers.ts
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
Labels: 6.5, cla: yes

#71 Fix integration test for wrangler schema editor
  app/cdap/components/DataPrep/TopPanel/index.js
  app/cdap/components/DataPrep/store/DataPrepActionCreator.js
  cypress/integration/plugin.schemaeditor.spec.ts
Labels: cla: yes

#68 Connection Management Fixes and Grouping by Types
  app/cdap/components/AbstractWidget/ConnectionsWidget/index.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/Connections/Browser/SidePanel/apiHelpers.ts
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/CreateConnectionModal/index.tsx
  app/cdap/components/Home/index.js
  app/cdap/components/NamespaceAdmin/Tabs.tsx
  app/cdap/components/PipelineConfigurations/ConfigurationsContent/PushdownTabContent.tsx
  app/cdap/components/PushdownConfig/index.tsx
  app/cdap/components/Table/TableCell.tsx
Labels: 6.5, cherry-pick, cla: yes

#72 Fix integration test for wrangler schema editor
  app/cdap/components/DataPrep/TopPanel/index.js
  app/cdap/components/DataPrep/store/DataPrepActionCreator.js
  cypress/integration/plugin.schemaeditor.spec.ts
Labels: 6.5, bug, cherry-pick, cla: yes

#69 [CDAP-18107] Convert secondary buttons in conneciton management to outlined style
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Connections/CreateConnectionBtn/index.tsx
Labels: UI, cla: yes

#73 [CDAP-18106] Pluralize entity counts in connection browser
  app/cdap/components/Connections/Browser/GenericBrowser/EntityCount.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/apiHelpers.ts
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/text/text-en.yaml
Labels: UI, bug, cla: yes

#74 [CDAP-18069] Test connection improvements: messaging and field-level errors
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/index.tsx
  app/cdap/components/Connections/Create/index.tsx
Labels: UI, cla: yes

#70 [CDAP-18070] Add description to connection browse modal
  app/cdap/components/AbstractWidget/ConnectionsWidget/index.tsx
Labels: UI, cla: yes

#75 [CDAP-18069] [CDAP-18070] [CDAP-18106] [CDAP-18107] cherry-pic to 6.5
  app/cdap/components/AbstractWidget/ConnectionsWidget/index.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/EntityCount.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/apiHelpers.ts
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/index.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/CreateConnectionBtn/index.tsx
  app/cdap/text/text-en.yaml
Labels: 6.5, UI, bug, cherry-pick, cla: yes
