Repository cdapio/cdap-ui, pull requests merged in 2021-04, with the labels that each got.

#3 [CDAP-17624] Start E2E tests on Google Cloud Build
  .gitignore
  cloudbuild.yaml
  cloudbuild/builder/Dockerfile
  cloudbuild/cloudbuildrun.sh
  cypress.json
  package.json
  sandboxjs/bamboo_plan_info.json
  sandboxjs/fetch_sandbox.js
  sandboxjs/package.json
  sandboxjs/setup_cloudbuild.js
  sandboxjs/setup_gitpod.js
  sandboxjs/start.js
  sandboxjs/unzip.js
  sandboxjs/yarn.lock
Labels: 6.5

#10 [CDAP-17283] Fixes the name of record type to conform to Avro Schema spec
  app/cdap/components/AbstractWidget/SchemaEditor/Context/SchemaGenerator.ts
Labels: 6.5, bug, cherry-pick

#9 [CDAP-17776]: Widget for Conditional Aggregate Functions
  app/cdap/components/AbstractWidget/FunctionDropdownAliasWidget/FuctionDropdownRow.tsx
Labels: 6.5, cherry-pick
