Repository cdapio/cdap-ui, pull requests merged in 2021-11, with the labels that each got.

#234 [CDAP-18589] Add dynamic execution configuration
  app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/EngineConfigTabContent.scss
  app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/index.js
  app/cdap/components/PipelineConfigurations/PipelineConfigConstants.tsx
  app/cdap/components/PipelineConfigurations/Store/index.js
  app/cdap/services/ThemeHelper.ts
  app/cdap/services/global-constants.js
  app/cdap/text/text-en.yaml
  app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config-ctrl.js
  app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config.html
  app/hydrator/services/create/stores/config-store.js
  server/config/themes/default.json
Labels: cla: yes

#235 [RELEASE-6.5.1] Bump to SNAPSHOT
  pom.xml
Labels: cla: yes, automated-release

#227 podesta - transformations styling
  app/cdap/components/Replicator/Create/Content/SearchBox/index.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/index.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/styles.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/table.tsx
Labels: cla: yes, replication transformations

#236 Repl transforms - connecting ui with backend/add delete transformations
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/TransformAdd.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/TransformDelete.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/addToTransforms.ts
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/index.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/styles.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/table.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/types.ts
  app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  app/cdap/components/Replicator/Create/index.tsx
  app/cdap/components/Replicator/types.ts
Labels: cla: yes, replication transformations

#237 podesta - replication transformations / connected nov
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/TransformAdd.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/TransformDelete.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/index.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/reducer.ts
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/styles.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/table.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/types.ts
  app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  app/cdap/components/Replicator/Create/index.tsx
  app/cdap/components/Replicator/types.ts
  app/cdap/components/StatusButton/StatusButton.stories.tsx
  app/cdap/components/StatusButton/index.tsx
  app/cdap/components/StatusButton/styles.tsx
Labels: UI, cla: yes, replication transformations

#238 trasnformations error banner if error on add tranformation request
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/TransformAdd.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/addToTransforms.ts
  app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  app/cdap/components/Replicator/Create/index.tsx
  app/cdap/components/Replicator/Create/steps.tsx
Labels: cla: yes, replication transformations

#240 cherry pick transformations for nov
  .storybook/ThemeDecorator.tsx
  .storybook/Welcome.tsx
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/preview.js
  app/cdap/components/ConfigurationGroup/index.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Replicator/Create/Content/SearchBox/index.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/TransformAdd.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/TransformDelete.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/addToTransforms.ts
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/index.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/reducer.ts
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/styles.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/table.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/types.ts
  app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  app/cdap/components/Replicator/Create/index.tsx
  app/cdap/components/Replicator/Create/steps.tsx
  app/cdap/components/Replicator/types.ts
  app/cdap/components/StatusButton/StatusButton.stories.tsx
  app/cdap/components/StatusButton/icons.tsx
  app/cdap/components/StatusButton/index.tsx
  app/cdap/components/StatusButton/styles.tsx
  package.json
  yarn.lock
Labels: cla: yes, replication transformations

#242 had to save tables and columns before assessing tables for adding tra…
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/TransformAdd.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/TransformDelete.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/addToTransforms.ts
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/index.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/table.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/types.ts
  app/cdap/components/Replicator/Create/index.tsx
  app/cdap/components/Replicator/Create/steps.tsx
  app/cdap/components/Replicator/types.ts
Labels: cla: yes

#250 fix pipeline spec since blank macros are no longer allowed
  cypress/integration/pipeline.spec.ts
  package.json
Labels: cla: yes

#246 Cherry pick/242 odf
  .github/workflows/node.js.yml
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/TransformAdd.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/TransformDelete.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/addToTransforms.ts
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/index.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/table.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/types.ts
  app/cdap/components/Replicator/Create/index.tsx
  app/cdap/components/Replicator/Create/steps.tsx
  app/cdap/components/Replicator/types.ts
Labels: cherry-pick, cla: yes

#245 fix ignoring of click event on navbar items when market modal is active
  app/cdap/components/AppHeader/AppToolBar/AppToolbar.tsx
  app/cdap/components/AppHeader/BrandImage.tsx
Labels: cla: yes

#241 React migration: Metadata summary page
  app/cdap/api/search.js
  app/cdap/components/Metadata/ComplexSchema/__tests__/helper.test.ts
  app/cdap/components/Metadata/ComplexSchema/helper.ts
  app/cdap/components/Metadata/ComplexSchema/index.tsx
  app/cdap/components/Metadata/SearchResults/ResultList/index.tsx
  app/cdap/components/Metadata/SearchResults/index.tsx
  app/cdap/components/Metadata/SearchSummary/EntityProperties/index.tsx
  app/cdap/components/Metadata/SearchSummary/EntitySchema/index.tsx
  app/cdap/components/Metadata/SearchSummary/EntityTags/index.tsx
  app/cdap/components/Metadata/SearchSummary/EntityTopBar/index.tsx
  app/cdap/components/Metadata/SearchSummary/__tests__/helper.test.ts
  app/cdap/components/Metadata/SearchSummary/helper.ts
  app/cdap/components/Metadata/SearchSummary/index.tsx
  app/cdap/components/Metadata/index.tsx
  app/cdap/text/text-en.yaml
Labels: cla: yes

#251 display 0 as the value for scale and precision of decimal fields
  app/cdap/components/AbstractWidget/SchemaEditor/RowButtons/FieldAttributes/DecimalAttributes.tsx
Labels: cla: yes

#253 Pipeline studio: Removes validation for hidden plugin fields
  app/cdap/services/PipelineErrorFactory.js
  app/hydrator/services/create/stores/config-store.js
  app/hydrator/services/plugin-config-factory.js
Labels: cla: yes

#252 persist entered values when toggling macro button in pipeline studio …
  app/cdap/components/ConfigurationGroup/PropertyRow/index.tsx
Labels: cla: yes

#156 [PLUGIN-769] Added dropdown menu option to call the explode record directive
  app/cdap/components/DataPrep/Directives/Explode/index.js
  app/cdap/text/text-en.yaml
Labels: cla: yes

#256 Adds redirection for metadata summary page & page titles
  app/cdap/components/Metadata/Home/index.tsx
  app/cdap/components/Metadata/SearchResults/index.tsx
  app/cdap/components/Metadata/SearchSummary/EntityTopBar/index.tsx
  app/cdap/components/Metadata/SearchSummary/index.tsx
  app/cdap/text/text-en.yaml
  app/tracker/routes.js
Labels: cla: yes

#257 Fixing version to a previous version of node-gyp to fix build failures
  pom.xml
Labels: cla: yes

#258 Connection creation: Navigate to the newly created connection
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/__tests__/helper.test.ts
  app/cdap/components/Connections/helper.ts
Labels: cla: yes

#255 Allows partial heirarchy selection for BQ, GCS & Spanner
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/Browser/index.tsx
  app/cdap/components/shared/Table/TableHeader.tsx
Labels: cla: yes

#259 Revert "Pipeline studio: Removes validation for hidden plugin fields"
  app/cdap/services/PipelineErrorFactory.js
  app/hydrator/services/create/stores/config-store.js
  app/hydrator/services/plugin-config-factory.js
Labels: cla: yes

#261 Fixes cypress tests for connection creation
  cypress/integration/wrangler.bigquery.spec.ts
  cypress/integration/wrangler.gcs.spec.ts
  cypress/integration/wrangler.spanner.spec.ts
  cypress/support/commands.ts
  cypress/typings/index.d.ts
Labels: cla: yes

#260 updates for node v16.13.0
  .github/workflows/node.js.yml
  app/cdap/components/shared/AppDetailedView/AppDetailedView.scss
  package.json
  pom.xml
  yarn.lock
Labels: cla: yes
