Repository cdapio/cdap-ui, pull requests merged in 2021-08, with the labels that each got.

#157 [CDAP-18294] Shorten pushdown description
  app/cdap/components/PushdownConfig/index.tsx
Labels: 6.5, cherry-pick, cla: yes

#158 [CDAP-18294] Shorten pushdown description
  app/cdap/components/PushdownConfig/index.tsx
Labels: 6.5, cla: yes

#159 [CDAP-18295] Make use of default connection an explicit flag
  app/cdap/components/Connections/ConnectionsContext/index.tsx
  app/cdap/components/Connections/index.tsx
  app/cdap/components/DataPrepConnections/PluginConnectionBrowser/index.tsx
  app/cdap/components/DataPrepHome/index.js
Labels: cla: yes

#161 [CDAP-18295] Make use of default connection an explicit flag (cherry pick)
  app/cdap/components/Connections/ConnectionsContext/index.tsx
  app/cdap/components/Connections/index.tsx
  app/cdap/components/DataPrepConnections/PluginConnectionBrowser/index.tsx
  app/cdap/components/DataPrepHome/index.js
Labels: 6.5, cherry-pick, cla: yes

#162 Merge pull request #160 from cdapio/bugfix-ui/cdap-18283-2
  app/cdap/components/AbstractWidget/index.tsx
  app/cdap/components/ConfigurationGroup/PropertyRow/index.tsx
  app/cdap/components/ConfigurationGroup/index.tsx
  app/cdap/components/DataPrepConnections/PluginConnectionBrowser/index.tsx
Labels: 6.5, cherry-pick, cla: yes

#163 [CDAP-18294] Update pushdown desc again
  app/cdap/components/PushdownConfig/index.tsx
Labels: cla: yes

#164 [CDAP-18294] Update pushdown desc again [cherry-pick]
  app/cdap/components/PushdownConfig/index.tsx
Labels: 6.5, cherry-pick, cla: yes

#165 CDAP-18263 | disable link if non editable profiles
  app/cdap/components/PipelineDetails/ProfilesListView/ProfileCustomizePopover/ProfileCustomizeContent/index.js
  app/cdap/components/PipelineDetails/ProfilesListView/ProfileCustomizePopover/ProfileCustomizePopover.scss
  app/cdap/components/PipelineDetails/ProfilesListView/ProfileCustomizePopover/index.js
Labels: bug, 6.5, UI, cla: yes

#166 [CDAP-18327] Stop preview pipeline if preview panel closed
  app/hydrator/controllers/create/toppanel-ctrl.js
Labels: cla: yes

#167 [CDAP-18327] Stop preview pipeline if preview panel closed [cherry pick]
  app/hydrator/controllers/create/toppanel-ctrl.js
Labels: cherry-pick, 6.5, cla: yes

#172 Merge pull request #168 from cdapio/bugfix-ui/CDAP-18324
  app/cdap/components/Connections/Browser/GenericBrowser/apiHelpers.ts
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
Labels: cherry-pick, 6.5, cla: yes

#170 CDAP-18264 | Link to replicator in profile associations
  app/cdap/components/Cloud/Profiles/DetailView/Content/ProfileAssociations/index.js
  app/cdap/components/Replicator/Detail/DetailContent/index.tsx
  app/cdap/components/Replicator/List/Deployed/index.tsx
  app/cdap/components/Replicator/utilities/index.ts
Labels: bug, UI, cla: yes

#171 CDAP 18339 - check if use connection is true before using connection name in plugin connection browser
  app/cdap/components/AbstractWidget/ToggleSwitchWidget/index.tsx
  app/cdap/components/AbstractWidget/index.tsx
  app/cdap/components/DataPrepConnections/PluginConnectionBrowser/index.tsx
Labels: bug, 6.5, UI, cla: yes

#173 Merge pull request #171 from cdapio/bugfix-ui/CDAP-18339
  app/cdap/components/AbstractWidget/ToggleSwitchWidget/index.tsx
  app/cdap/components/AbstractWidget/index.tsx
  app/cdap/components/DataPrepConnections/PluginConnectionBrowser/index.tsx
Labels: bug, cherry-pick, 6.5, cla: yes

#175 [CDAP-18341] Make sure file upload calls onWorkspaceCreate instead of redirecting for 6.5
  app/cdap/components/Connections/Upload/index.tsx
Labels: bug, cherry-pick, 6.5, cla: yes

#174 [CDAP-18341] Make sure file upload calls onWorkspaceCreate instead of redirecting
  app/cdap/components/Connections/Upload/index.tsx
Labels: bug, cla: yes

#177 Allows spaces in connection name
  app/cdap/components/Connections/Create/index.tsx
Labels: cla: no

#178 [CDAP-18346] Allows spaces in connection name
  app/cdap/components/Connections/Create/index.tsx
Labels: cherry-pick, 6.5, cla: yes

#176 [CDAP-17753] Fix incorrect cron default
  app/cdap/services/global-constants.js
Labels: cla: yes

#179 [CDAP-18326] Restore edit mode as a read-only view
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/index.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/CreateConnectionModal/index.tsx
  app/cdap/components/NamespaceAdmin/Connections.tsx
Labels: cla: yes

#180 [CDAP-18326] and [CDAP-17753] - combined cherrypick
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/index.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/CreateConnectionModal/index.tsx
  app/cdap/components/NamespaceAdmin/Connections.tsx
  app/cdap/services/global-constants.js
Labels: cherry-pick, 6.5, cla: yes

#183 [CDAP-17594] Field Level Lineage - Change link label
  app/cdap/components/FieldLevelLineage/v2/TopPanel/index.tsx
Labels: cla: yes

#181 [CDAP-18364] Sync connection and path changes in GenericBrowser
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/Browser/index.tsx
  app/cdap/components/Connections/Home.tsx
Labels: bug, cla: yes

#186 [CDAP-18364] Sync connection and path changes in GenericBrowser for 6.5
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/Browser/index.tsx
  app/cdap/components/Connections/Home.tsx
Labels: bug, cherry-pick, 6.5, cla: yes

#185 [CDAP-11521] Show stats (no. of rows and columns) of data in data prep
  app/cdap/components/DataPrep/TopPanel/TopPanel.scss
  app/cdap/components/DataPrep/TopPanel/index.js
  app/cdap/text/text-en.yaml
Labels: cla: yes

#187 [CDAP-17840] System Admin Profiles pane show View All link twice
  app/cdap/components/Cloud/Profiles/ListView/index.js
Labels: cla: yes

#188 [CDAP-18383] Don't attempt default conn in namespace
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/index.tsx
Labels: cla: yes

#190 Fix scheduling tests
  cypress/integration/pipeline.studio.scheduling.spec.ts
Labels: cla: yes

#191 Lauren/aug 18 cherry picks
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/index.tsx
  cypress/integration/pipeline.studio.scheduling.spec.ts
Labels: cherry-pick, 6.5, cla: yes

#192 Adds security flags for UI cookies
  app/cdap/main.js
  app/login/login.js
  server/express.js
Labels: cla: yes

#194 Remove -SNAPSHOT for release
  pom.xml
Labels: cla: yes

#193 Removes sourcemap from production cdap.js build
  webpack.config.cdap.js
Labels: cla: yes

#189 [CDAP-18387] Starting cdap-ui dev server using 'yarn run hmr-dev-w' fails on Linux
  webpack.config.cdap.dev.js
Labels: cla: yes

#197 Bumped versions to next SNAPSHOT.
  pom.xml
Labels: cla: yes
