Repository cdapio/cdap-ui, pull requests merged in 2021-07, with the labels that each got.

#81 [CDAP-18151] Properly Surface UI SSL Initialization Errors
  server.js
Labels: cla: yes

#77 [CDAP-17947] Fix the height of engine custom configs
  app/directives/my-pipeline-configurations/my-pipeline-configurations.less
Labels: cla: yes

#78 [CDAP-17973] Improve error messaging in connection browser
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/Create/index.tsx
Labels: cla: yes

#82 [CDAP-18151] Properly surface UI SSL Initialization Errors 6.5 Cherry-Pick
  server.js
Labels: cla: yes

#80 Connection management UX update
  app/cdap/components/AbstractWidget/ConnectionsWidget/index.tsx
  app/cdap/components/Alert/index.js
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/index.tsx
  app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
  app/cdap/components/EmptyMessageContainer/index.js
  app/cdap/components/StatusAlertMessage/index.js
Labels: 6.5, bug, cla: yes

#83 Connection management bug fixes
  app/cdap/components/AbstractWidget/ConnectionsWidget/index.tsx
  app/cdap/components/Alert/index.js
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/index.tsx
  app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
  app/cdap/components/EmptyMessageContainer/index.js
  app/cdap/components/StatusAlertMessage/index.js
Labels: 6.5, bug, cherry-pick, cla: yes

#84 [CDAP-18113] Add file upload capability to connection management
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/Connections/Browser/index.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/Routes.tsx
  app/cdap/components/Connections/Upload/index.tsx
  app/cdap/components/FileDnD/index.js
  app/cdap/components/Home/index.js
Labels: cla: yes

#86 [CDAP-18147] Fix profiles count to take from Profile store
  app/cdap/components/NamespaceAdmin/ComputeProfiles.tsx
  app/cdap/components/NamespaceAdmin/Metrics/ProfileMetric.tsx
  app/cdap/components/NamespaceAdmin/Metrics/index.tsx
  app/cdap/components/NamespaceAdmin/index.tsx
  app/cdap/components/NamespaceAdmin/store/ActionCreator.ts
Labels: bug, cla: yes

#85 [CDAP-18094] Add abilty to disable certain connection types
  app/cdap/api/connections.ts
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
  app/cdap/components/Connections/ConnectionsContext/index.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/Create/reducer.ts
  app/cdap/components/Connections/index.tsx
Labels: cla: yes

#88 [PLUGIN-703] Attempt to fix issue with conditionValue
  app/cdap/components/AbstractWidget/FunctionDropdownAliasWidget/FuctionDropdownRow.tsx
Labels: UI, bug, cla: yes

#87 Connection mgmt cherry pick 65
  app/cdap/api/connections.ts
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
  app/cdap/components/Connections/Browser/index.tsx
  app/cdap/components/Connections/ConnectionsContext/index.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/Create/reducer.ts
  app/cdap/components/Connections/Routes.tsx
  app/cdap/components/Connections/Upload/index.tsx
  app/cdap/components/Connections/index.tsx
  app/cdap/components/FileDnD/index.js
  app/cdap/components/Home/index.js
  app/cdap/components/NamespaceAdmin/ComputeProfiles.tsx
  app/cdap/components/NamespaceAdmin/Metrics/ProfileMetric.tsx
  app/cdap/components/NamespaceAdmin/Metrics/index.tsx
  app/cdap/components/NamespaceAdmin/index.tsx
  app/cdap/components/NamespaceAdmin/store/ActionCreator.ts
Labels: 6.5, bug, cherry-pick, cla: yes

#89 [CDAP-17947] [CDAP-17973] [PLUGIN-703] Cherry-pick for 6.5
  app/cdap/components/AbstractWidget/FunctionDropdownAliasWidget/FuctionDropdownRow.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/directives/my-pipeline-configurations/my-pipeline-configurations.less
Labels: 6.5, UI, bug, cherry-pick, cla: yes

#90 Exclude connections from macro treatment
  app/cdap/components/ConfigurationGroup/PropertyRow/index.tsx
  app/hydrator/controllers/create/toppanel-ctrl.js
Labels: cla: yes

#91 Exclude connections from macro treatment (6.5 cherry pick)
  app/cdap/components/ConfigurationGroup/PropertyRow/index.tsx
  app/hydrator/controllers/create/toppanel-ctrl.js
Labels: 6.5, bug, cherry-pick, cla: yes

#76 CDAP-17948/Fixes styling on num rows preview config
  app/cdap/components/PipelineConfigurations/ConfigurationsContent/ConfigurationsContent.scss
  app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config.html
Labels: UI, bug, cla: yes

#92 [CDAP-18173] Fix unmount bug in ConfigurationGroup
  app/cdap/components/ConfigurationGroup/index.tsx
  app/cdap/services/helpers.js
Labels: cla: yes

#93 CDAP 18202 - Fix popover for connections so long names don't make them unusable
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
Labels: 6.5, UI, cla: yes

#96 [CDAP-18173] Fix unmount bug in ConfigurationGroup (cherry pick 6.5)
  app/cdap/components/ConfigurationGroup/index.tsx
  app/cdap/services/helpers.js
Labels: cla: yes

#94 [CDAP-18005] Re-enable Wrangler E2E tests to work with connection management
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/SearchField.tsx
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/Connections/Create/CategorizedConnectors/ActiveTab.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Connections/CreateConnectionBtn/index.tsx
  app/cdap/components/Table/index.tsx
  cypress/integration/pipeline.multiselect.spec.ts
  cypress/integration/wrangler.bigquery.spec.ts
  cypress/integration/wrangler.gcs.spec.ts
  cypress/integration/wrangler.spanner.spec.ts
  cypress/support/commands.ts
  cypress/support/constants.ts
  cypress/typings/index.d.ts
Labels: UI, cla: yes

#97 [CDAP-18118] Pushdown check user plugin first
  app/cdap/components/PushdownConfig/index.tsx
Labels: cla: yes

#95 CDAP-18193 - Adds optional prop to errorBanner and Alert components to make page interactable when used as a toast.
  app/cdap/components/Alert/Alert.scss
  app/cdap/components/Alert/index.js
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/ErrorBanner/index.tsx
Labels: 6.5, UI, cla: yes

#98 [CDAP-18080] Improve errors for bad conn. names
  app/cdap/components/Connections/Create/index.tsx
Labels: cla: yes

#79 CDAP-17946 / check if errors are arrays before forEaching them
  app/cdap/services/helpers.js
Labels: UI, bug, cla: yes

#101 [CDAP-18206] List each connection type name only once in Wrangler
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
Labels: UI, bug, cla: yes

#99 Slightly clarify errors from GenericBrowser
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
Labels: cla: yes

#100 [CDAP-17639] Trim whitespace in macro args
  app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/RuntimeArgsRow.tsx
  app/directives/my-pipeline-runtime-args/my-pipeline-runtime-args.js
Labels: cla: yes

#102 Cherry pick pull request 95, 93, 79, 76 onto release branch 6.5
  app/cdap/components/Alert/Alert.scss
  app/cdap/components/Alert/index.js
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/ErrorBanner/index.tsx
  app/cdap/components/PipelineConfigurations/ConfigurationsContent/ConfigurationsContent.scss
  app/cdap/services/helpers.js
  app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config.html
Labels: 6.5, cherry-pick, cla: yes

#105 [CDAP-18231] Improve error message for worksapce creation failures in Wrangler
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
Labels: UI, cla: yes

#104 [CDAP-18005] Re-enable Wrangler E2E tests to work with connection management
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/SearchField.tsx
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/Connections/Create/CategorizedConnectors/ActiveTab.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Connections/CreateConnectionBtn/index.tsx
  app/cdap/components/Table/index.tsx
  cypress/integration/pipeline.multiselect.spec.ts
  cypress/integration/wrangler.bigquery.spec.ts
  cypress/integration/wrangler.gcs.spec.ts
  cypress/integration/wrangler.spanner.spec.ts
  cypress/support/commands.ts
  cypress/support/constants.ts
  cypress/typings/index.d.ts
Labels: 6.5, UI, cherry-pick, cla: yes

#103 Lauren/cherry pick text fixes
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/RuntimeArgsRow.tsx
  app/directives/my-pipeline-runtime-args/my-pipeline-runtime-args.js
Labels: 6.5, cherry-pick, cla: yes

#106 [CDAP-18118] Pushdown check user plugin first (cherry-pick)
  app/cdap/components/PushdownConfig/index.tsx
Labels: 6.5, cherry-pick, cla: yes

#107 [CDAP-18206] [CDAP-18231] Connection management fixes to 6.5
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
Labels: 6.5, bug, cherry-pick, cla: yes

#110 CDAP 18245 - right aligns the popover buttons for connections in wrangler
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
Labels: 6.5, UI, bug, cla: yes

#108 Hides side panel for GCS connections browse
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
  app/cdap/components/Connections/ConnectionsContext/index.tsx
  app/cdap/components/Connections/Home.tsx
  app/cdap/components/Connections/Routes.tsx
  app/cdap/components/Connections/index.tsx
  app/cdap/components/DataPrepConnections/PluginConnectionBrowser/index.tsx
Labels: 6.5, UI, bug, cla: yes

#111 Merge pull request #110 from cdapio/bugfix-ui/CDAP-18245
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
Labels: 6.5, UI, cherry-pick, cla: yes

#113 [CDAP-18244] Fix Cypress test breaks: 1 bug, 1 DOM change, flaky pipelines tests
  app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/RuntimeArgsRow.tsx
  app/directives/my-pipeline-runtime-args/my-pipeline-runtime-args.js
  cypress/fixtures/draft_for_upgrade.json
  cypress/fixtures/fll_airport_pipeline2.json
  cypress/fixtures/logs_generator-cdap-data-pipeline.json
  cypress/fixtures/missing-artifact-pipeline.json
  cypress/fixtures/old_userstore_draft.json
  cypress/fixtures/pipeline1.json
  cypress/fixtures/pipeline_old.json
  cypress/fixtures/pipeline_with_macros.json
  cypress/support/commands.ts
Labels: UI, bug, cla: yes

#63 Bugfix UI/cdap 17806 - Save more often in the replication create flow.
  app/cdap/components/Replicator/Create/Content/Advanced/index.tsx
  app/cdap/components/Replicator/Create/Content/NameDescription/index.tsx
  app/cdap/components/Replicator/Create/Content/PluginConfig/index.tsx
  app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
Labels: UI, cla: yes

#112 Cherry pick pull request #108
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
  app/cdap/components/Connections/ConnectionsContext/index.tsx
  app/cdap/components/Connections/Home.tsx
  app/cdap/components/Connections/Routes.tsx
  app/cdap/components/Connections/index.tsx
  app/cdap/components/DataPrepConnections/PluginConnectionBrowser/index.tsx
Labels: 6.5, UI, cherry-pick, cla: yes

#109 CDAP-18139 - fixes add connection button while browsing from inside of wrangler
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
  app/cdap/components/Connections/CreateConnectionBtn/index.tsx
Labels: 6.5, UI, bug, cla: yes

#115 Merge pull request #63 from cdapio/bugfix-ui/CDAP-17806
  app/cdap/components/Replicator/Create/Content/Advanced/index.tsx
  app/cdap/components/Replicator/Create/Content/NameDescription/index.tsx
  app/cdap/components/Replicator/Create/Content/PluginConfig/index.tsx
  app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
Labels: 6.5, UI, cherry-pick, cla: yes

#116 Merge pull request #109 from cdapio/bugfix-ui/CDAP-18139
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
  app/cdap/components/Connections/CreateConnectionBtn/index.tsx
Labels: 6.5, UI, cherry-pick, cla: yes

#118 CDAP-18235 - Adds schema name to unique key generation for tables in replicator
  app/cdap/components/Replicator/Create/Content/SelectTables/ManualSelectTable/index.tsx
  app/cdap/components/Replicator/utilities/index.ts
Labels: 6.5, UI, bug, cla: yes

#117 [CDAP-18152] Tweak styles for pushdown
  app/cdap/components/PipelineConfigurations/ConfigurationsContent/PushdownTabContent.tsx
  app/cdap/components/PipelineConfigurations/index.js
  app/cdap/components/PushdownConfig/index.tsx
  app/cdap/components/Tabs/TabHead/TabHead.scss
  app/cdap/text/text-en.yaml
Labels: 6.5, UI, cla: yes

#120 Merge pull request #118 from cdapio/bugfix-ui/CDAP-18235
  app/cdap/components/Replicator/Create/Content/SelectTables/ManualSelectTable/index.tsx
  app/cdap/components/Replicator/utilities/index.ts
Labels: 6.5, UI, cherry-pick, cla: yes

#121 [CDAP-18152] Tweak styles for pushdown (cherry pick version)
  app/cdap/components/PipelineConfigurations/ConfigurationsContent/PushdownTabContent.tsx
  app/cdap/components/PipelineConfigurations/index.js
  app/cdap/components/PushdownConfig/index.tsx
  app/cdap/components/Tabs/TabHead/TabHead.scss
  app/cdap/text/text-en.yaml
Labels: 6.5, cherry-pick, cla: yes

#119 [CDAP-18017] Don't send hidden fields with get schema
  app/cdap/components/ConfigurationGroup/index.tsx
Labels: UI, bug, cla: yes

#122 [CDAP-18246] Remove Edit option for connections
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/NamespaceAdmin/Connections.tsx
Labels: UI, bug, cla: yes

#123 [CDAP-18244] Fix Cypress test breaks: 1 bug, 1 DOM change, flaky pipelines tests for 6.5 (take 2)
  app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/RuntimeArgsRow.tsx
  app/directives/my-pipeline-runtime-args/my-pipeline-runtime-args.js
  cypress/fixtures/draft_for_upgrade.json
  cypress/fixtures/fll_airport_pipeline2.json
  cypress/fixtures/logs_generator-cdap-data-pipeline.json
  cypress/fixtures/missing-artifact-pipeline.json
  cypress/fixtures/old_userstore_draft.json
  cypress/fixtures/pipeline1.json
  cypress/fixtures/pipeline_old.json
  cypress/fixtures/pipeline_with_macros.json
  cypress/support/commands.ts
Labels: 6.5, UI, bug, cherry-pick, cla: yes

#124 [CDAP-18017] [CDAP-18246] Connection management fixes to 6.5
  app/cdap/components/ConfigurationGroup/index.tsx
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/NamespaceAdmin/Connections.tsx
Labels: 6.5, UI, bug, cherry-pick, cla: yes

#125 [CDAP-18258] Restore data-cy for Add Connection button
  app/cdap/components/Connections/CreateConnectionBtn/index.tsx
Labels: bug, cla: yes

#126 [CDAP-18258] Restore data-cy for Add Connection button for 6.5
  app/cdap/components/Connections/CreateConnectionBtn/index.tsx
Labels: 6.5, bug, cherry-pick, cla: yes

#127 CDAP - 18252 zindex on add connection modal
  app/cdap/components/Connections/CreateConnectionModal/index.tsx
Labels: 6.5, UI, bug, cla: yes

#130 [CDAP-18261] Clear filter in connection browser when new results loaded
  app/cdap/components/ConfigurationGroup/index.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Table/index.tsx
Labels: bug, cla: yes

#131 [CDAP-18261] Clear filter in connection browser when new results loaded for 6.5
  app/cdap/components/ConfigurationGroup/index.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Table/index.tsx
Labels: 6.5, bug, cherry-pick, cla: yes

#128 CDAP 18260 - fixes background color of add connection button
  app/cdap/components/Connections/AddConnectionBtnModal/index.tsx
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
Labels: 6.5, UI, bug, cla: yes

#132 Merge pull request #128 from cdapio/bugfix-ui/CDAP-18260
  app/cdap/components/Connections/AddConnectionBtnModal/index.tsx
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
Labels: 6.5, UI, cherry-pick, cla: yes

#133 [CDAP-18231] Display server-provided errors in GenericBrowser
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
Labels: cla: yes

#135 [CDAP-18231] Display server-provided errors in GenericBrowser (cherry pick)
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
Labels: 6.5, cherry-pick, cla: yes

#134 Update Insights to new connection manager API
  app/cdap/api/dataprep.js
  app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/BrowserData/TableContents.tsx
  app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/BucketData/TableContents.tsx
  app/cdap/components/DataPrep/DataPrepVisualization/index.js
  app/cdap/components/DataPrep/TopPanel/index.js
  app/cdap/components/DataPrep/index.js
  app/cdap/components/DataPrep/store/DataPrepActionCreator.js
  app/cdap/components/DataPrep/store/DataPrepActions.js
  app/cdap/components/DataPrep/store/index.ts
  app/cdap/components/DataPrepHome/index.js
  app/cdap/components/Experiments/store/CreateExperimentActionCreator.js
Labels: cla: yes

#138 [CDAP-18243] Allow selection connection during browse if no connection specified
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
  app/cdap/components/Connections/ConnectionsContext/index.tsx
  app/cdap/components/Connections/Home.tsx
  app/cdap/components/Connections/Routes.tsx
  app/cdap/components/Connections/index.tsx
  app/cdap/components/DataPrepConnections/PluginConnectionBrowser/index.tsx
Labels: bug, cla: yes

#136 [No JIRA] Add `yarn dev` multi-job watch command
  package.json
  yarn.lock
Labels: cla: yes

#140 [PLUGIN-752] Increase column width and show tooltip for connector type description
  app/cdap/components/Connections/Create/CategorizedConnectors/ActiveTab.tsx
  app/cdap/components/NamespaceAdmin/Connections.tsx
Labels: bug, cla: yes

#139 [CDAP-18093] Redirect to default connection
  app/cdap/components/Connections/index.tsx
Labels: cla: yes

#129 Merge pull request #127 from cdapio/bugfix-ui/CDAP-18252
  app/cdap/components/Connections/CreateConnectionModal/index.tsx
Labels: 6.5, UI, cherry-pick, cla: yes

#141 [CDAP-18269] Don't show orphan errors twice when testing a connection
  app/cdap/components/ConfigurationGroup/index.tsx
  app/cdap/components/Connections/Create/index.tsx
Labels: bug, cla: yes

#137 Bugfix/cdap 18267 Removes duplicate getworkspace call during re-render
  app/cdap/components/DataPrep/index.js
Labels: 6.5, cla: yes

#142 [CDAP-18243] [CDAP-18269] [PLUGIN-752] Connection management fixes for 6.5
  app/cdap/components/ConfigurationGroup/index.tsx
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
  app/cdap/components/Connections/ConnectionsContext/index.tsx
  app/cdap/components/Connections/Create/CategorizedConnectors/ActiveTab.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/Home.tsx
  app/cdap/components/Connections/Routes.tsx
  app/cdap/components/Connections/index.tsx
  app/cdap/components/DataPrepConnections/PluginConnectionBrowser/index.tsx
  app/cdap/components/NamespaceAdmin/Connections.tsx
Labels: 6.5, bug, cherry-pick, cla: yes

#145 [CDAP-18093] Redirect to default connection [cherry pick, remade]
  app/cdap/components/Connections/index.tsx
Labels: 6.5, cherry-pick, cla: yes

#146 Makes runtime args tab in inbound trigger scrollable
  app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/Tabs/RuntimeArgsTab/index.js
Labels: 6.5, UI, bug, cla: yes

#147 Makes runtime args tab in inbound trigger scrollable
  app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/Tabs/RuntimeArgsTab/index.js
Labels: 6.5, cherry-pick, cla: yes

#144 [CDAP-18209] Update insights page to new connection manager API
  app/cdap/api/dataprep.js
  app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/BrowserData/TableContents.tsx
  app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/BucketData/TableContents.tsx
  app/cdap/components/DataPrep/DataPrepVisualization/index.js
  app/cdap/components/DataPrep/TopPanel/index.js
  app/cdap/components/DataPrep/index.js
  app/cdap/components/DataPrep/store/DataPrepActionCreator.js
  app/cdap/components/DataPrep/store/DataPrepActions.js
  app/cdap/components/DataPrep/store/index.ts
  app/cdap/components/DataPrepHome/index.js
  app/cdap/components/Experiments/store/CreateExperimentActionCreator.js
Labels: cherry-pick, cla: yes

#149 [CDAP-17629] Add special case null check for missing field
  app/hydrator/services/hydrator-upgrade-service.js
Labels: cla: yes

#148 CDAP 18283 - Add plugin name to use as reference name default
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
Labels: 6.5, UI, bug, cla: yes

#151 [CDAP-18289] UI should hide the disabled connection types
  app/cdap/components/Connections/index.tsx
Labels: cla: yes

#152 Lauren/cherrypick fixes jul29
  app/cdap/components/Connections/index.tsx
  app/hydrator/services/hydrator-upgrade-service.js
Labels: cla: yes

#153 CDAP-18227 - use correct object query to display correct number of tasks
  app/cdap/components/Replicator/Detail/index.tsx
Labels: 6.5, UI, bug, cla: yes

#154 don't add reference name for connections
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
Labels: UI, cla: yes

#155 CherryPick 153 - use correct object query to display correct number of tasks
  app/cdap/components/Replicator/Detail/index.tsx
Labels: 6.5, cherry-pick, cla: yes
