Repository cdapio/cdap-ui, pull requests merged in 2021-12, with the labels that each got.

#264 Fixes js error while closing kafka connection creation dialog
  app/cdap/components/DataPrepConnections/KafkaConnection/HostPortEditor/index.js
Labels: cla: yes

#265 Fixes js error while closing kafka connection creation dialog
  app/cdap/components/DataPrepConnections/KafkaConnection/HostPortEditor/index.js
Labels: cherry-pick, 6.5, cla: yes

#254 fix page nav when setting runtime args in control center
  app/cdap/components/EntityListView/SearchStore/ActionCreator.js
Labels: cla: yes

#263 Revert "updates for node v16.13.0"
  .github/workflows/node.js.yml
  app/cdap/components/shared/AppDetailedView/AppDetailedView.scss
  package.json
  pom.xml
  yarn.lock
Labels: cla: yes

#267 bump up version for CDAP 6.7.0-SNAPSHOT
  pom.xml
Labels: cla: yes

#269 Fixing version to a previous version of node-gyp to fix build failures
  pom.xml
Labels: cla: yes

#270 Update Cypress sandbox download to get new version 6.7.0-SNAPSHOT
  sandboxjs/bamboo_plan_info.json
Labels: cla: yes

#273 bump up version for CDAP 6.6 SNAPSHOT
  pom.xml
Labels: cla: yes

#271 Pipeline studio: Removes validation for hidden plugin fields
  app/cdap/services/PipelineErrorFactory.js
  app/hydrator/services/create/stores/config-store.js
  app/hydrator/services/plugin-config-factory.js
Labels: cla: yes

#280 Replication Transforms - add rename and mask directives
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/TransformAdd.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/addToTransforms.ts
Labels: replication transformations

#287 BUILD ERROR - explicitly install npmcli/fs globally before node gyp
  pom.xml
Labels: bug
