Repository cdapio/cdap-ui, pull requests merged in 2021-05, with the labels that each got.

#18 [CDAP-17958] Set node to version 12 for all cloud build steps
  cloudbuild.yaml
Labels: 6.5, UI

#15 CDAP-17750: Performance improvements to Hierarchy widget
  app/cdap/components/AbstractWidget/HierarchyWidget/HierarchyTreeNode/ListBoxComponent.tsx
  app/cdap/components/AbstractWidget/HierarchyWidget/HierarchyTreeNode/index.tsx
Labels: 6.5, cherry-pick

#22 fix build and checkstyle
  checkstyle.xml
  cloudbuild/builder/Dockerfile
Labels: 6.5, bug

#26 [CDAP-17873] Integrate with connector plugins API
  app/cdap/api/connections.ts
  app/cdap/components/Connections/Browser/GenericBrowser/apiHelpers.ts
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/Browser/index.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/Create/reducer.ts
Labels: 6.5

#25 [CDAP-17876] Add confirmation step before deleting connection or driver
  app/cdap/components/CaskWizards/ArtifactUpload/index.js
  app/cdap/components/NamespaceAdmin/Connections.tsx
  app/cdap/components/NamespaceAdmin/Drivers/index.tsx
  app/cdap/components/NamespaceAdmin/store/ActionCreator.ts
Labels: 6.5

#32 [CDAP-17988] Minor improvements to Connections browser loading behavior
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/Connections/Browser/index.tsx
Labels: 6.5

#31 [CDAP-18016] Generic connection browser: Add error display
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
Labels: 6.5, UI

#33 [CDAP-17874] Connection management add ability to add and import conn…
  app/cdap/components/AbstractWidget/ConnectionsWidget/index.tsx
  app/cdap/components/Connections/AddConnectionBtnModal/index.tsx
  app/cdap/components/Connections/CreateConnectionModal/index.tsx
  app/cdap/components/Connections/ImportConnectionBtn/index.tsx
  app/cdap/components/EntityTopPanel/EntityBreadCrumb.tsx
  app/cdap/components/EntityTopPanel/EntityTitle.tsx
  app/cdap/components/NamespaceAdmin/Connections.tsx
  app/cdap/components/PipelineModal/index.tsx
Labels: 6.5
