Repository cdapio/cdap-ui, pull requests merged in 2022-02, with the labels that each got.

#333 [CDAP-18795] Use preview max limit setting from cConf for 6.6
  app/hydrator/services/create/stores/config-store.js
  server/express.js
Labels: cherry-pick, 6.6

#329 Auto-Scaling as an alternative compute Profile
  app/cdap/components/Cloud/Profiles/AutoScaleBadge/index.tsx
  app/cdap/components/Cloud/Profiles/CreateView/CreateProfileActionCreator.js
  app/cdap/components/Cloud/Profiles/CreateView/CreateProfileStore.js
  app/cdap/components/Cloud/Profiles/CreateView/PropertyRow/index.tsx
  app/cdap/components/Cloud/Profiles/CreateView/index.js
  app/cdap/components/Cloud/Profiles/DetailView/Content/BasicInfo/index.js
  app/cdap/components/Cloud/Profiles/ListView/ListView.scss
  app/cdap/components/Cloud/Profiles/ListView/index.js
  app/cdap/components/PipelineConfigurations/PipelineConfigurations.scss
  app/cdap/components/PipelineConfigurations/index.js
  app/cdap/components/PipelineDetails/PipelineModeless/PipelineModeless.scss
  app/cdap/components/PipelineDetails/ProfilesListView/ProfileCustomizePopover/ProfileCustomizeContent/index.js
  app/cdap/components/PipelineDetails/ProfilesListView/ProfileCustomizePopover/ProfilePropertyRow/index.tsx
  app/cdap/components/PipelineDetails/ProfilesListView/ProfilesListViewInPipeline.scss
  app/cdap/components/PipelineDetails/ProfilesListView/index.js
  app/cdap/text/text-en.yaml
Labels: cherry-pick, 6.6

#337 Fixes the logic to show auto scale badge in profile list/details page
  app/cdap/components/Cloud/Profiles/AutoScaleBadge/index.tsx
  app/cdap/components/Cloud/Profiles/DetailView/Content/BasicInfo/index.js
  app/cdap/components/Cloud/Profiles/ListView/index.js
  app/cdap/components/PipelineDetails/ProfilesListView/index.js
Labels: cherry-pick, 6.6

#338 [CDAP-18801] Fix LogViewer event propagation for new React version in 6.6
  app/cdap/components/Popover/index.js
Labels: cherry-pick, 6.6

#340 [CDAP-18816] Allow max preview rows config to override hard-coded limit
  app/hydrator/services/create/stores/config-store.js
Labels: cherry-pick, 6.6

#343 Remove transformations when table is removed and other fixes
  app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/index.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/addToTransforms.ts
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/index.tsx
  app/cdap/components/Replicator/Create/Content/SelectTables/ManualSelectTable/index.tsx
  app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  app/cdap/components/Replicator/Create/Content/StepButtons/index.tsx
  app/cdap/components/Replicator/Create/Content/index.tsx
  app/cdap/components/Replicator/Create/LeftPanel/index.tsx
  app/cdap/components/Replicator/Create/TopPanel/index.tsx
  app/cdap/components/Replicator/Create/index.tsx
  app/cdap/components/Replicator/utilities/index.ts
Labels: replication transformations

#353 Adds plugin type & name to fetch plugin properties contextually
  app/cdap/components/Connections/Browser/GenericBrowser/apiHelpers.ts
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
  app/cdap/components/Connections/ConnectionsContext/index.tsx
  app/cdap/components/Connections/index.tsx
  app/cdap/services/PipelineMetricsStore/ActionCreator.js
  app/cdap/services/PipelineMetricsStore/index.js
  app/directives/dag-plus/my-dag-ctrl.js
Labels: bug

#357 Restore pipeline level profile customisations
  app/cdap/components/PipelineDetails/ProfilesListView/index.js
  app/cdap/text/text-en.yaml
Labels: 6.6

#358 Label changes for auto scaling compute profile
  app/cdap/text/text-en.yaml
Labels: cherry-pick, 6.6

#362 Update total cores field during profile customisation
  app/cdap/components/PipelineDetails/ProfilesListView/index.js
Labels: cherry-pick, 6.6

#365 Fix height error on main page
  app/cdap/main.js
Labels: 6.7

#378 Fixes partial connection selection in BQ and database plugins
  app/cdap/components/Connections/Browser/GenericBrowser/BrowserTable.tsx
  app/cdap/components/DataPrepConnections/PluginConnectionBrowser/index.tsx
Labels: 6.7
