Repository cdapio/cdap-ui, pull requests merged in 2022-08, with the labels that each got.

#577 CDAP-19450 Fix metric graph gap handling
  app/cdap/components/PipelineSummary/RunsGraphHelpers.js
  app/cdap/components/PipelineSummary/__tests__/RunsGraphHelpers.test.ts
Labels: bug

#579 CDAP-19450 Fix metric graph gap handling for 6.7
  app/cdap/components/PipelineSummary/RunsGraphHelpers.js
  app/cdap/components/PipelineSummary/__tests__/RunsGraphHelpers.test.ts
Labels: bug, cherry-pick, 6.7

#604 Add external links to toolbar cog menu
  app/cdap/components/shared/AppHeader/AppToolBar/AppToolbarMenu.tsx
  server/config/ui-settings.json
  server/express.js
Labels: UI
