Repository cdapio/cdap-ui, pull requests merged in 2022-01, with the labels that each got.

#298 [CDAP-18065] Handle schemas with nested records of the same name
  app/cdap/components/AbstractWidget/SchemaEditor/Context/SchemaGenerator.ts
  app/cdap/components/AbstractWidget/SchemaEditor/Context/SchemaParser.ts
  app/cdap/components/AbstractWidget/SchemaEditor/Context/__tests__/SchemaManager.tests.ts
  app/cdap/components/AbstractWidget/SchemaEditor/Context/__tests__/schemas.js
Labels: bug

#262 Adds metadata lineage page
  app/cdap/api/search.js
  app/cdap/components/Metadata/Home/index.tsx
  app/cdap/components/Metadata/Lineage/LineageDiagram/index.tsx
  app/cdap/components/Metadata/Lineage/LineageDiagram/styles.tsx
  app/cdap/components/Metadata/Lineage/ProgramModal/index.tsx
  app/cdap/components/Metadata/Lineage/__tests__/helper.test.ts
  app/cdap/components/Metadata/Lineage/helper.ts
  app/cdap/components/Metadata/Lineage/index.tsx
  app/cdap/components/Metadata/Lineage/styles.tsx
  app/cdap/components/Metadata/Lineage/timeRangeOptions.ts
  app/cdap/components/Metadata/SearchResults/ResultList/index.tsx
  app/cdap/components/Metadata/SearchResults/index.tsx
  app/cdap/components/Metadata/SearchSummary/EntityTopBar/index.tsx
  app/cdap/components/Metadata/SearchSummary/index.tsx
  app/cdap/components/Metadata/__tests__/urlHelper.test.ts
  app/cdap/components/Metadata/index.tsx
  app/cdap/components/Metadata/urlHelper.ts
  app/cdap/text/text-en.yaml
  app/tracker/routes.js
  package.json
  yarn.lock
Labels: cla: yes

#308 Update pom.xml to use older node-gyp version
  pom.xml
Labels: 6.6

#309 Update bamboo_plan_info.json
  sandboxjs/bamboo_plan_info.json
Labels: 6.6

#321 Feature flags using react context api
  app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  app/cdap/components/Replicator/Create/Content/StepButtons/index.tsx
  app/cdap/components/Replicator/Create/Content/index.tsx
  app/cdap/components/Replicator/Create/LeftPanel/index.tsx
  app/cdap/components/Replicator/Create/TopPanel/index.tsx
  app/cdap/components/Replicator/Create/index.tsx
  app/cdap/components/Replicator/Create/steps.tsx
  app/cdap/main.js
  app/cdap/services/react/customHooks/useFeatureFlag.ts
  app/cdap/services/react/providers/featureFlagProvider.tsx
  server.js
  server/config/development/cdap.json
  server/express.js
Labels: replication transformations

#324 merge feature flags and transformation feature flags into 6.6
  app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  app/cdap/components/Replicator/Create/Content/StepButtons/index.tsx
  app/cdap/components/Replicator/Create/Content/index.tsx
  app/cdap/components/Replicator/Create/LeftPanel/index.tsx
  app/cdap/components/Replicator/Create/TopPanel/index.tsx
  app/cdap/components/Replicator/Create/index.tsx
  app/cdap/components/Replicator/Create/steps.tsx
  app/cdap/services/react/customHooks/useFeatureFlag.ts
  app/cdap/services/react/providers/featureFlagProvider.tsx
  server.js
  server/config/development/cdap.json
  server/express.js
Labels: replication transformations, 6.6
