Repository cdapio/cdap-ui, pull requests merged in 2022-11, with the labels that each got.

#708 Correct plugin names for studio
  app/cdap/components/hydrator/components/SidePanel/SidePanel.tsx
  app/cdap/services/filters/removeCamelCase.ts
Labels: 6.8

#711 Cherry pick #708 into 6.8
  app/cdap/components/hydrator/components/SidePanel/SidePanel.tsx
  app/cdap/services/filters/removeCamelCase.ts
Labels: 6.8

#710 Cherry pick #700 into 6.8
  app/cdap/components/hydrator/components/SidePanel/SidePanel.tsx
  app/cdap/components/hydrator/components/SidePanel/sharedStyled.tsx
Labels: 6.8

#718 [cdap-20008] - watch number of plugins
  app/cdap/components/hydrator/components/SidePanel/ChangeVersionMenu.tsx
  app/cdap/components/hydrator/components/SidePanel/SidePanel.tsx
Labels: 6.8

#701 Review: CDAP 19699 Fix - Breadcrumb not clickable in Grid Page when No Data Screen is displayed
  app/cdap/components/ConnectionList/Components/SubHeader/styles.ts
  app/cdap/components/GridTable/index.tsx
  app/cdap/components/NoRecordScreen/styles.ts
  app/cdap/components/WrangleHome/Components/OngoingDataExplorationCard/index.tsx
Labels: wrangler-2022

#681 CDAP 19925 Unit Testing for Grid Page
  app/cdap/components/ConnectionList/index.tsx
  app/cdap/components/GridTable/__test__/GridTable.test.tsx
  app/cdap/components/GridTable/components/Breadcrumb/__test__/Breadcrumb.test.tsx
  app/cdap/components/GridTable/components/Breadcrumb/index.tsx
  app/cdap/components/GridTable/components/GridHeaderCell/index.tsx
  app/cdap/components/GridTable/components/GridKPICell/__test__/GridKPICell.test.tsx
  app/cdap/components/GridTable/components/GridKPICell/index.tsx
  app/cdap/components/GridTable/components/GridTextCell/__test__/GridTextCell.test.tsx
  app/cdap/components/GridTable/components/GridTextCell/index.tsx
  app/cdap/components/GridTable/components/Typography/__test__/TypographyComponent.test.tsx
  app/cdap/components/GridTable/components/Typography/index.tsx
  app/cdap/components/GridTable/index.tsx
  app/cdap/components/WrangleHome/Components/OngoingDataExplorationCard/index.tsx
Labels: wrangler-2022

#679 CDAP-19925 Unit Testing for Connections List Page
  app/cdap/components/ConnectionList/Components/ConnectionTabs/__test__/ConnectionTabs.test.tsx
  app/cdap/components/ConnectionList/Components/ConnectionTabs/index.tsx
  app/cdap/components/ConnectionList/Components/ConnectionTabs/mock/mockTabsDataWithBrowse.tsx
  app/cdap/components/ConnectionList/Components/ConnectionTabs/mock/mockTabsDataWithBrowseIndex.tsx
  app/cdap/components/ConnectionList/Components/ConnectionTabs/mock/mockTabsTestData.tsx
  app/cdap/components/ConnectionList/Components/CustomTooltip/__test__/CustomTooltip.test.tsx
  app/cdap/components/ConnectionList/Components/TabLabelCanBrowse/__test__/TabLabelCanBrowse.test.tsx
  app/cdap/components/ConnectionList/Components/TabLabelCanBrowse/index.tsx
  app/cdap/components/ConnectionList/Components/TabLabelCanBrowse/mock/mockConnectorTypeData.tsx
  app/cdap/components/ConnectionList/Components/TabLabelCanSample/__test__/TabLabelCanSample.test.tsx
  app/cdap/components/ConnectionList/Components/TabLabelCanSample/index.tsx
  app/cdap/components/ConnectionList/Components/TabLabelCanSample/mock/mockConnectorTypeData.ts
  app/cdap/components/ConnectionList/__test__/ConnectionList.test.tsx
  app/cdap/components/ConnectionList/index.tsx
  app/cdap/components/ConnectionList/mock/mockDataForConnectionList.ts
  app/cdap/components/GridTable/components/GridHeaderCell/__test__/GridHeaderCell.test.tsx
  app/cdap/components/GridTable/components/GridHeaderCell/index.tsx
  app/cdap/components/GridTable/components/mock/mockDataForGrid.ts
Labels: build, wrangler-2022

#745 [CDAP-13130] - fix broken pipeline upgrade
  app/hydrator/services/hydrator-upgrade-service.js
Labels: 6.8

#747 Add edit studio template
  app/cdap/components/hydrator/components/SidePanel/SidePanel.tsx
Labels: 6.8

#749 Cherry pick #745 into 6.8 - fix broken pipeline upgrade
  app/hydrator/services/hydrator-upgrade-service.js
Labels: 6.8

#750 Cherry pick #747 into 6.8 - add edit studio template
  app/cdap/components/hydrator/components/SidePanel/SidePanel.tsx
Labels: 6.8

#751 [CDAP-20040] - direct table log viewer page to the chart log viewer url
  app/cdap/components/PipelineSummary/LogsMetricsGraph/index.js
Labels: 6.8

#753 Cherry pick #751 into 6.8 - direct table log viewer page to the chart log viewer url
  app/cdap/components/PipelineSummary/LogsMetricsGraph/index.js
Labels: 6.8

#798 Review: CDAP 19917 - Snackbar
  app/cdap/components/ConnectionList/Components/SubHeader/index.tsx
  app/cdap/components/GridTable/index.tsx
  app/cdap/components/Snackbar/__test__/Snackbar.test.tsx
  app/cdap/components/Snackbar/components/Transition/__test__/Transition.test.tsx
  app/cdap/components/Snackbar/components/Transition/index.tsx
  app/cdap/components/Snackbar/index.tsx
  app/cdap/components/Snackbar/useSnackbar.ts
  app/cdap/components/WrangleHome/Components/OngoingDataExploration/index.tsx
  app/cdap/components/WrangleHome/Components/WrangleCard/__test__/WrangleCard.test.tsx
  app/cdap/components/WrangleHome/Components/WrangleCard/mock/wrangleCardMockData.ts
  app/cdap/components/common/DrawerWidget/IconStore/Underline.tsx
  app/cdap/components/common/DrawerWidget/__test__/DrawerWidget.test.tsx
  app/cdap/text/text-en.yaml
  src/e2e-test/features/snackbar.feature
  src/e2e-test/java/io/cdap/cdap/ui/stepsdesign/SnackBar.java
  src/e2e-test/java/io/cdap/cdap/ui/utils/Constants.java
Labels: build, wrangler-2022
