Repository cdapio/cdap-ui, pull requests merged in 2022-04, with the labels that each got.

#407 CDAP-19025 Add fields to node when adding to canvas so hidden required fields can be checked
  app/hydrator/controllers/create/leftpanel-ctrl.js
Labels: bug

#413 CDAP-19025 Add fields to node when adding to canvas so hidden required fields can be checked
  app/hydrator/controllers/create/leftpanel-ctrl.js
Labels: bug, cherry-pick, 6.7

#402 Angular studio/tooltip search
  app/cdap/components/hydrator/components/SidePanel/SidePanel.tsx
  app/cdap/components/hydrator/components/SidePanel/helpers.tsx
  app/hydrator/leftpanel.less
  package.json
  yarn.lock
Labels: a2react

#442 CDAP-18913 CDAP-18959 Cherrypick deprecation warnings to 6.7
  app/cdap/components/DataPrep/Directives/Parse/Modals/CSVModal.js
  app/cdap/components/PipelineConfigurations/ConfigurationsContent/ConfigurationsContent.scss
  app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/EngineConfigTabContent.scss
  app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/index.js
  app/cdap/text/text-en.yaml
  app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config.html
Labels: bug, cherry-pick, 6.7

#449 CDAP-19057 Support default connections that don't provide an artifact version for 6.7
  app/cdap/components/Connections/Browser/ParsingConfigModal/store.tsx
Labels: bug, cherry-pick, 6.7

#446 Adds required field validation for connection creation form
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
Labels: cherry-pick, 6.7

#459 CDAP-18954 - use new error message structure
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/table.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/types.ts
  app/cdap/components/Replicator/Create/index.tsx
  app/cdap/components/Replicator/utilities/__tests__/utilities.test.ts
  app/cdap/components/Replicator/utilities/index.ts
Labels: replication transformations, 6.7

#464 CDAP-19077 Fix size of source parsing dialog whether or not error is shown
  app/cdap/components/Connections/Browser/ParsingConfigModal/index.tsx
Labels: bug

#465 CDAP-19077 Fix size of source parsing dialog whether or not error is shown for 6.7
  app/cdap/components/Connections/Browser/ParsingConfigModal/index.tsx
Labels: bug, cherry-pick, 6.7

#463 fix the pipeline cypress test
  app/cdap/components/TriggeredPipelines/TriggeredPipelineRow.tsx
Labels: bug

#475 CDAP-19147 Use plugin widget filters to show/hide properties in source parsing
  app/cdap/components/Connections/Browser/ParsingConfigModal/index.tsx
  app/cdap/components/Connections/Browser/ParsingConfigModal/store.tsx
  app/cdap/components/shared/ConfigurationGroup/utilities/DynamicPluginFilters.ts
Labels: bug
