Repository cdapio/cdap-ui, pull requests merged in 2022-05, with the labels that each got.

#478 CDAP-19147 Use plugin widget filters to show/hide properties in source parsing for 6.7
  app/cdap/components/Connections/Browser/ParsingConfigModal/index.tsx
  app/cdap/components/Connections/Browser/ParsingConfigModal/store.tsx
  app/cdap/components/shared/ConfigurationGroup/utilities/DynamicPluginFilters.ts
Labels: bug, cherry-pick, 6.7

#481 CDAP-19158 Upload schema when parsing from source for 6.7
  app/cdap/components/AbstractWidget/SchemaEditor/SchemaHelpers.ts
  app/cdap/components/Connections/Browser/ParsingConfigModal/ImportFileButton.tsx
  app/cdap/components/Connections/Browser/ParsingConfigModal/index.tsx
  app/cdap/components/Connections/Browser/ParsingConfigModal/store.tsx
  app/cdap/components/PluginSchemaEditor/index.tsx
  app/cdap/components/shared/Buttons/PrimaryContainedButton/index.tsx
  app/cdap/components/shared/Buttons/PrimaryOutlinedButton/index.tsx
  app/cdap/components/shared/Buttons/PrimaryTextButton/index.tsx
  app/cdap/components/shared/ConfigurationGroup/PropertyRow/DescriptionTooltip.tsx
  app/cdap/text/text-en.yaml
Labels: cherry-pick, 6.7

#482 [CDAP-19175] replicator fix set initial transformation
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/index.tsx
  app/cdap/components/Replicator/utilities/index.ts
Labels: bug, replication transformations, 6.7

#487 CDAP 19205 - Pipelines - remove system tags
  app/cdap/components/shared/Tags/index.js
Labels: 6.7

#488 Cherry pick 487
  app/cdap/components/shared/Tags/index.js
Labels: cherry-pick, 6.7

#483 [CDAP-19160] replicator using the new api to get assessTable response
  app/cdap/api/replicator.js
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/index.tsx
  app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/types.ts
  app/cdap/components/Replicator/types.ts
Labels: bug, replication transformations, 6.7

#496 CDAP-19217 Connection creation: Fetch plugin properties for non-system scope correctly for 6.7
  app/cdap/components/Connections/Create/reducer.ts
Labels: bug, cherry-pick, 6.7

#500 CDAP-19270 Remove scope/version selection from connection creation
  app/cdap/components/Connections/Create/CategorizedConnectors/ActiveTab.tsx
Labels: bug, cherry-pick, 6.7

#502 CDAP-19198 CDAP-19200 Make pre-configured connections view-only
  app/cdap/components/Connections/Browser/SidePanel/CategorizedConnections.tsx
  app/cdap/components/Connections/Browser/SidePanel/index.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/ConnectionConfigForm.tsx
  app/cdap/components/Connections/Create/ConnectionConfiguration/index.tsx
  app/cdap/components/Connections/Create/index.tsx
  app/cdap/components/Connections/Create/reducer.ts
  app/cdap/components/Connections/CreateConnectionModal/index.tsx
  app/cdap/components/Connections/types.ts
  app/cdap/components/NamespaceAdmin/Connections.tsx
  app/cdap/components/NamespaceAdmin/store/index.ts
  app/cdap/text/text-en.yaml
Labels: bug

#497 Change z index of layer so that it sits above everything on page for select
  app/cdap/components/AbstractWidget/FormInputs/Select/index.tsx
Labels: bug, 6.7

#512 CDAP-19285 Fix compute profile customizations
  app/cdap/components/PipelineConfigurations/ConfigurationsContent/ConfigModelessActionButtons/index.js
Labels: bug

#515 CDAP-19313 Disable HTTP-to-Websocket migration while troubleshooting error handling
  app/cdap/services/datasource/DataSourceConfigurer.js
Labels: bug

#517 CDAP-19190 CDAP-19201 Lineage graph fixes in React
  app/cdap/components/Metadata/Lineage/LineageDiagram/index.tsx
  app/cdap/components/Metadata/Lineage/ProgramModal/index.tsx
Labels: bug

#516 CDAP-19313 Fix HTTP migration E2E test failures
  app/cdap/api/market.js
  app/cdap/services/datasource/DataSourceConfigurer.js
  app/cdap/services/datasource/DataSourceHttp.ts
  app/cdap/services/datasource/requestTypes.ts
  server/express.js
Labels: bug

#518 CDAP-19323 Tweak HTTP error handling to return response object
  app/cdap/services/datasource/DataSourceHttp.ts
Labels: bug

#524 use secrets in github workflow
  .github/workflows/node.js.yml
  .github/workflows/trigger.yml
  selenium/support/constants.ts
Labels: build
