Repository cdapio/cdap-ui, pull requests merged in 2023-08, with the labels that each got.

#1069 [CDAP-20726] - adds conditional cookie banner for notifying users for analytics
  app/cdap/components/CookieBanner/constants.ts
  app/cdap/components/CookieBanner/index.tsx
  app/cdap/main.js
  app/cdap/text/text-en.yaml
  server/express.js
  src/e2e-test/features/wrangler.gcs.feature
Labels: build, 6.9.2

#1082 Cherry pick #1069 into release 6.9.2
  app/cdap/components/CookieBanner/constants.ts
  app/cdap/components/CookieBanner/index.tsx
  app/cdap/main.js
  app/cdap/text/text-en.yaml
  server/express.js
Labels: 6.9.2

#1099 Bump version to 6.7.4-SNAPSHOT
  pom.xml
Labels: build

#1100 Bump SNAPSHOT for sandbox in release/6.7
  sandboxjs/sandbox_version.json
Labels: build

#1101 [RELEASE-6.9.2] Remove SNAPSHOTs
  pom.xml
Labels: automated-release
