Repository cdapio/cdap-ui, pull requests merged in 2023-04, with the labels that each got.

#971 Remove snapshot
  pom.xml
Labels: build

#977 bugfix(PLUGIN-1566/CDAP-20568): Send correct pipeline ID info in trigger payload
  app/cdap/components/PipelineTriggers/PipelineListCompositeTab/index.tsx
  app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/ScheduleRuntimeArgsActions.js
  app/cdap/components/PipelineTriggers/store/PipelineTriggersActionCreator.ts
  app/cdap/components/PipelineTriggers/store/ScheduleTypes.ts
  src/e2e-test/features/pipeline.triggers.feature
  src/e2e-test/java/io/cdap/cdap/ui/stepsdesign/PipelineTriggers.java
Labels: build, 6.8, 6.9.1

#984 Merge develop release69
  app/cdap/components/EntityTopPanel/EntityBreadCrumb.tsx
  app/cdap/components/EntityTopPanel/EntityTitle.tsx
  app/cdap/components/FieldLevelLineage/v2/TopPanel/index.tsx
  app/cdap/components/PipelineTriggers/PipelineListCompositeTab/index.tsx
  app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/ScheduleRuntimeArgsActions.js
  app/cdap/components/PipelineTriggers/store/PipelineTriggersActionCreator.ts
  app/cdap/components/PipelineTriggers/store/ScheduleTypes.ts
  app/cdap/components/shared/ConfigurationGroup/utilities/DynamicPluginFilters.ts
  app/cdap/components/shared/ConfigurationGroup/utilities/__tests__/DynamicPluginFilters.test.ts
  src/e2e-test/features/pipeline.triggers.feature
  src/e2e-test/java/io/cdap/cdap/ui/stepsdesign/PipelineTriggers.java
Labels: build

#988 6.9.1cherrypick(CDAP-20563) Use relative paths to redirect from login page
  app/cdap/services/redirect-to-login.js
  app/hydrator/main.js
  app/login/login.js
  app/tracker/main.js
Labels: build, 6.9.1

#992 [RELEASE-6.8.2] Bump to SNAPSHOT
  pom.xml
Labels: automated-release

#990 fix: use Object.keys in the feature flag for loop
  app/cdap/components/shared/ConfigurationGroup/utilities/DynamicPluginFilters.ts
  src/e2e-test/features/logviewer.feature
  src/e2e-test/java/io/cdap/cdap/ui/stepsdesign/CommonSteps.java
  src/e2e-test/java/io/cdap/cdap/ui/stepsdesign/PipelineRuntimeMacros.java
Labels: build, 6.9.1

#987 6.8.3cherrypick(CDAP-20563): Use relative paths to redirect from login page
  app/cdap/services/redirect-to-login.js
  app/hydrator/main.js
  app/login/login.js
  app/tracker/main.js
Labels: build, 6.8.3

#986 6.8.3cherrypick(PLUGIN-1566/CDAP-20568): fix the pipeline ID sent in trigger information
  app/cdap/components/PipelineTriggers/PipelineListCompositeTab/index.tsx
  app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/ScheduleRuntimeArgsActions.js
  app/cdap/components/PipelineTriggers/store/PipelineTriggersActionCreator.ts
  app/cdap/components/PipelineTriggers/store/ScheduleTypes.ts
Labels: build, 6.8.3

#993 chore(6.8.3): bump e2e sandbox version
  sandboxjs/sandbox_version.json
Labels: build, 6.8.3

#994 chore(6.9.1): bump e2e sandbox version to 6.9.1
  sandboxjs/sandbox_version.json
Labels: build, 6.9.1
