Repository cdapio/cdap-ui, pull requests merged in 2023-05, with the labels that each got.

#999 Revert "chore: add optional run status in logviewer e2e test"
  src/e2e-test/features/logviewer.feature
  src/e2e-test/java/io/cdap/cdap/ui/stepsdesign/CommonSteps.java
Labels: build

#1003 CDAP-20603 Ensure error messages are shown when creating a Wrangler workspace for 6.9
  app/cdap/components/Connections/Browser/GenericBrowser/index.tsx
Labels: bug, cherry-pick, 6.9.1

#1015 fix(CDAP-20655): Only show "AND", "OR" and "PROGRAM_STATUS" triggers in UI
  app/cdap/components/PipelineTriggers/store/PipelineTriggersActionCreator.ts
Labels: build, 6.9.1, 6.8.3

#1017 cherrypick(CDAP-20655): Only show "AND", "OR" and "PROGRAM_STATUS" triggers in UI
  app/cdap/components/PipelineTriggers/store/PipelineTriggersActionCreator.ts
Labels: cherry-pick, 6.8.3

#1016 cherrypick(CDAP-20655): Only show "AND", "OR" and "PROGRAM_STATUS" triggers in UI
  app/cdap/components/PipelineTriggers/store/PipelineTriggersActionCreator.ts
Labels: cherry-pick, 6.9.1

#1021 fix(CDAP-20660): ignore checking pipelineID info for pre-6.8 triggers' argument mapping properties
  app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/ScheduleRuntimeArgsActions.js
Labels: build, 6.8.3

#1027 Adds google analytics to content security policy
  server/express.js
Labels: 6.9.1

#1033 [RELEASE-6.8.3] Remove SNAPSHOTs
  pom.xml
Labels: automated-release
